### ISSUE TITLE
Error with peewee

### ISSUE THREAD

**Issue by JimScope** [roshnet/blogstate-api#6]
Error, database must be initialized before opening a connection

**Comment by roshnet** [comment]
Hey @JimScope, I think you might need to create the database launching the app. Please see if the following wiki could help you out - https://github.com/roshnet/blogstate-api/wiki/Configuration

Also, I think I should move the wiki to a more visible place (took me a while to recall where had I put it :smile:)

**Comment by JimScope** [comment]
thanks, it works! The wiki is hidden like a ninja 😂

**Comment by roshnet** [comment]
@JimScope Awesome, glad it worked! I've made changes to the wiki as well.
